version: '3.1'

services:
  # APIs
  graphql_api:
    build:
      context: ./api/
      dockerfile: graphql.Dockerfile
    ports:
      - 5000:80
    depends_on:
      - etl_database
      - elasticsearch
      - kibana
      - jaeger
      - country_database
      - fields_database
      - cache
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ElasticSearch__Url: ${ELASTICSEARCH_URL}
      TimeseriesDatabase__ConnectionString: Host=etl_database;Username=postgres;Password=password;Database=covid
      CountryDatabase__ConnectionString: mongodb://root:rootpassword@country_database:27017
      CountryDatabase__DatabaseName: covid
      FieldsDatabase__ConnectionString: mongodb://root:rootpassword@fields_database:27017
      FieldsDatabase__DatabaseName: covid
      Redis__Hosts__0__Host: cache
      Redis__Hosts__0__Port: 6379
    networks:
      - elastic
      - database
      - tracing

  grpc_api:
    build:
      context: ./api/
      dockerfile: grpc.Dockerfile
    ports:
      - 6000:80
    depends_on:
      - etl_database
      - elasticsearch
      - kibana
      - jaeger
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ElasticSearch__Url: ${ELASTICSEARCH_URL}
      TimeseriesDatabase__ConnectionString: Host=etl_database;Username=postgres;Password=password;Database=covid
    networks:
      - elastic
      - database
      - tracing

  etl_database:
    image: postgres:latest
    volumes:
      - etl_database/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    networks:
      - database

  # jaeger:
  #   image: jaegertracing/all-in-one:latest
  #   ports:
  #       - "5775:5775/udp"
  #       - "6831:6831/udp"
  #       - "6832:6832/udp"
  #       - "5778:5778"
  #       - "16686:16686" # UI
  #       - "14268:14268"
  #       - "9411:9411"
  #   networks:
  #     - tracing

  country_database:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - country_database:/data/db
    networks:
      - database

  fields_database:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27018:27017
    volumes:
      - fields_database:/data/db
    networks:
      - database

  cache:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - cache_database:/data
    networks:
      - database

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.7.1
    ports:
      - 9200:9200
    volumes:
      - elasticsearch_database:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: kibana:7.7.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
    networks:
      - elastic

volumes:
  etl_database:
  elasticsearch_database:
  country_database:
  fields_database:
  cache_database:

networks:
  elastic:
    driver: bridge
  database:
    driver: bridge
  tracing:
    driver: bridge