version: '3.1'
services:
  etl_database:
    image: postgres:latest
    volumes:
      - etl_database/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${COVID_DATABASE_NAME}
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778"
        - "16686:16686"
        - "14268:14268"
        - "9411:9411"
volumes:
  etl_database: